server.port=8080
server.address=0.0.0.0

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

fileprocessing.threadpool.core-size=4
fileprocessing.threadpool.max-size=16
fileprocessing.threadpool.queue-capacity=200
fileprocessing.threadpool.resize-threshold=65
fileprocessing.threadpool.keep-alive-seconds=60
fileprocessing.threadpool.monitor-interval-seconds=1
